### ISSUE TITLE
Add include/exclude options for filtering modules

### ISSUE THREAD

**Issue by Holi0317** [webpack-contrib/babel-minify-webpack-plugin#50]
UglifyJS webpack plugin provides include/exclude options for filtering module list to be processed.

This can ignore minifying some modules that may have already been minified or will cause bug when passed through babili,

**Comment by rajchourasia** [comment]
Much needed

**Comment by evilebottnawi** [comment]
@Holi0317 @rajchourasia thanks, PR welcome :+1:

**Comment by damianobarbati** [comment]
+1!

**Comment by damianobarbati** [comment]
Anybody able to give a stab at this? 😅

**Comment by evilebottnawi** [comment]
@damianobarbati wip

**Comment by evilebottnawi** [comment]
@damianobarbati done in https://github.com/webpack-contrib/babel-minify-webpack-plugin/pull/75
