### ISSUE TITLE
Name change

### ISSUE THREAD

**Issue by boopathi** [webpack-contrib/babel-minify-webpack-plugin#54]
Babili has been renamed to babel-minify - Ref: https://github.com/babel/minify/issues/124 .. 

+ [x] Change this project to `babel-minify-webpack-plugin`.
+ [x] Update Travis service
+ [x] Update Appveyor service
+ [x] Update Codecov.io service
+ [x] Publish on npm with new name - after babel-minify is published. I already have the name on npm.

**Comment by d3viant0ne** [comment]
I'll take care of this shortly

**Comment by d3viant0ne** [comment]
The standard group needs to be given owner access to the new pacakge. i.e @bebraw & @d3viant0ne

**Comment by boopathi** [comment]
npm access rights: Done

**Comment by d3viant0ne** [comment]
Defaults is finished & in master ( seemed a good time to finish given this will be a new major version anyway ).

Given you are far more in the know as to when this is going to be published on the babel side, fire off a new release at your leisure.

**Comment by andykais** [comment]
need to update readme as well

**Comment by mgol** [comment]
[babel-preset-minify@0.2.0](https://www.npmjs.com/package/babel-preset-minify) has been published.
