### ISSUE TITLE
Unusable release on npm

### ISSUE THREAD

**Issue by xtuc** [webpack-contrib/babel-minify-webpack-plugin#59]
The release doesn't contain any files, see https://unpkg.com/babel-minify-webpack-plugin@0.0.0/.
Might be related to the recent name change https://github.com/webpack-contrib/babel-minify-webpack-plugin/issues/54.

**Comment by boopathi** [comment]
Published 🎉

**Comment by xtuc** [comment]
Thanks @boopathi.
