### ISSUE TITLE
invalid option topLevel

### ISSUE THREAD

**Issue by achmadk** [webpack-contrib/babel-minify-webpack-plugin#60]
> To enable optimizations to take place in the top level scope of the file, use topLevel: true in minifyOptions.

I tried to set `topLevel: true` in `minifyOption`. Unfortunately I got error `invalid option topLevel` when bundling. I have checked [this link](https://github.com/babel/minify/tree/master/packages/babel-preset-minify#options), there is no `topLevel` option in `babel-preset-minify`.

Maybe `topLevel` option will be provided in `pluginOpts` in the next release.

**Comment by boopathi** [comment]
Good catch. Thanks.

It's an option in [mangle](https://github.com/babel/minify/tree/master/packages/babel-plugin-minify-mangle-names#options). It'll be hoisted to `minifyOpts`, but for now only mangler supports it.

Feel free to PR.
