### ISSUE TITLE
Problem in strict-mode with ejs-templates

### ISSUE THREAD

**Issue by misantronic** [webpack-contrib/babel-minify-webpack-plugin#74]
In my project I use ejs-template which are compiled with `_.template` which makes use of the `with`-statement. This is not allowed in strict-mode so obviously babel-minify fails. Is there a way to tell babel to ignore this?

**Comment by evilebottnawi** [comment]
@misantronic Thanks for issue, but not related to this repo. Please create this issue here https://github.com/babel/minify/tree/master/packages/babel-preset-minify
